<?php

namespace Sunaoka\Aws\Structures\BCMDashboards\UpdateDashboard\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'AZ'|'INSTANCE_TYPE'|'LINKED_ACCOUNT'|'OPERATION'|'PURCHASE_TYPE'|'REGION'|'SERVICE'|'USAGE_TYPE'|'USAGE_TYPE_GROUP'|'RECORD_TYPE'|'RESOURCE_ID'|'SUBSCRIPTION_ID'|'TAG_KEY'|'OPERATING_SYSTEM'|'TENANCY'|'BILLING_ENTITY'|'RESERVATION_ID'|'COST_CATEGORY_NAME'|'DATABASE_ENGINE'|'LEGAL_ENTITY_NAME'|'SAVINGS_PLANS_TYPE'|'INSTANCE_TYPE_FAMILY'|'CACHE_ENGINE'|'DEPLOYMENT_OPTION'|'SCOPE'|'PLATFORM' $key
 * @property list<string> $values
 * @property list<'EQUALS'|'ABSENT'|'STARTS_WITH'|'ENDS_WITH'|'CONTAINS'|'GREATER_THAN_OR_EQUAL'|'CASE_SENSITIVE'|'CASE_INSENSITIVE'>|null $matchOptions
 */
class DimensionValues extends Shape
{
    /**
     * @param array{
     *     key: 'AZ'|'INSTANCE_TYPE'|'LINKED_ACCOUNT'|'OPERATION'|'PURCHASE_TYPE'|'REGION'|'SERVICE'|'USAGE_TYPE'|'USAGE_TYPE_GROUP'|'RECORD_TYPE'|'RESOURCE_ID'|'SUBSCRIPTION_ID'|'TAG_KEY'|'OPERATING_SYSTEM'|'TENANCY'|'BILLING_ENTITY'|'RESERVATION_ID'|'COST_CATEGORY_NAME'|'DATABASE_ENGINE'|'LEGAL_ENTITY_NAME'|'SAVINGS_PLANS_TYPE'|'INSTANCE_TYPE_FAMILY'|'CACHE_ENGINE'|'DEPLOYMENT_OPTION'|'SCOPE'|'PLATFORM',
     *     values: list<string>,
     *     matchOptions?: list<'EQUALS'|'ABSENT'|'STARTS_WITH'|'ENDS_WITH'|'CONTAINS'|'GREATER_THAN_OR_EQUAL'|'CASE_SENSITIVE'|'CASE_INSENSITIVE'>|null
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
