<?php

namespace Sunaoka\Aws\Structures\DevOpsAgent;

class DevOpsAgentClient extends \Aws\DevOpsAgent\DevOpsAgentClient
{
    use AssociateService\AssociateServiceTrait;
    use CreateAgentSpace\CreateAgentSpaceTrait;
    use CreateAsset\CreateAssetTrait;
    use CreateAssetFile\CreateAssetFileTrait;
    use CreateBacklogTask\CreateBacklogTaskTrait;
    use CreateChat\CreateChatTrait;
    use CreatePrivateConnection\CreatePrivateConnectionTrait;
    use CreateTrigger\CreateTriggerTrait;
    use DeleteAgentSpace\DeleteAgentSpaceTrait;
    use DeleteAsset\DeleteAssetTrait;
    use DeleteAssetFile\DeleteAssetFileTrait;
    use DeletePrivateConnection\DeletePrivateConnectionTrait;
    use DeleteTrigger\DeleteTriggerTrait;
    use DeregisterService\DeregisterServiceTrait;
    use DescribePrivateConnection\DescribePrivateConnectionTrait;
    use DisableOperatorApp\DisableOperatorAppTrait;
    use DisassociateService\DisassociateServiceTrait;
    use EnableOperatorApp\EnableOperatorAppTrait;
    use GetAccountUsage\GetAccountUsageTrait;
    use GetAgentSpace\GetAgentSpaceTrait;
    use GetAsset\GetAssetTrait;
    use GetAssetContent\GetAssetContentTrait;
    use GetAssetFile\GetAssetFileTrait;
    use GetAssociation\GetAssociationTrait;
    use GetBacklogTask\GetBacklogTaskTrait;
    use GetOperatorApp\GetOperatorAppTrait;
    use GetRecommendation\GetRecommendationTrait;
    use GetService\GetServiceTrait;
    use GetTrigger\GetTriggerTrait;
    use ListAgentSpaces\ListAgentSpacesTrait;
    use ListAssetFiles\ListAssetFilesTrait;
    use ListAssetTypes\ListAssetTypesTrait;
    use ListAssetVersions\ListAssetVersionsTrait;
    use ListAssets\ListAssetsTrait;
    use ListAssociations\ListAssociationsTrait;
    use ListBacklogTasks\ListBacklogTasksTrait;
    use ListChats\ListChatsTrait;
    use ListExecutions\ListExecutionsTrait;
    use ListGoals\ListGoalsTrait;
    use ListJournalRecords\ListJournalRecordsTrait;
    use ListPendingMessages\ListPendingMessagesTrait;
    use ListPrivateConnections\ListPrivateConnectionsTrait;
    use ListRecommendations\ListRecommendationsTrait;
    use ListServices\ListServicesTrait;
    use ListTagsForResource\ListTagsForResourceTrait;
    use ListTriggers\ListTriggersTrait;
    use ListWebhooks\ListWebhooksTrait;
    use RegisterService\RegisterServiceTrait;
    use SendMessage\SendMessageTrait;
    use TagResource\TagResourceTrait;
    use UntagResource\UntagResourceTrait;
    use UpdateAgentSpace\UpdateAgentSpaceTrait;
    use UpdateAsset\UpdateAssetTrait;
    use UpdateAssetFile\UpdateAssetFileTrait;
    use UpdateAssociation\UpdateAssociationTrait;
    use UpdateBacklogTask\UpdateBacklogTaskTrait;
    use UpdateGoal\UpdateGoalTrait;
    use UpdateOperatorAppIdpConfig\UpdateOperatorAppIdpConfigTrait;
    use UpdatePrivateConnectionCertificate\UpdatePrivateConnectionCertificateTrait;
    use UpdateRecommendation\UpdateRecommendationTrait;
    use UpdateTrigger\UpdateTriggerTrait;
    use ValidateAwsAssociations\ValidateAwsAssociationsTrait;
}
