<?php

namespace Sunaoka\Aws\Structures\MediaTailor\ConfigureLogsForPlaybackConfiguration\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property list<'RAW_ADS_RESPONSE'>|null $PublishOptInEventTypes
 * @property list<'AD_MARKER_FOUND'|'NON_AD_MARKER_FOUND'|'MAKING_ADS_REQUEST'|'MODIFIED_TARGET_URL'|'VAST_REDIRECT'|'EMPTY_VAST_RESPONSE'|'EMPTY_VMAP_RESPONSE'|'VAST_RESPONSE'|'REDIRECTED_VAST_RESPONSE'|'FILLED_AVAIL'|'FILLED_OVERLAY_AVAIL'|'BEACON_FIRED'|'WARNING_NO_ADVERTISEMENTS'|'WARNING_VPAID_AD_DROPPED'|'WARNING_URL_VARIABLE_SUBSTITUTION_FAILED'|'ERROR_UNKNOWN'|'ERROR_UNKNOWN_HOST'|'ERROR_DISALLOWED_HOST'|'ERROR_ADS_IO'|'ERROR_ADS_TIMEOUT'|'ERROR_ADS_RESPONSE_PARSE'|'ERROR_ADS_RESPONSE_UNKNOWN_ROOT_ELEMENT'|'ERROR_ADS_INVALID_RESPONSE'|'ERROR_VAST_REDIRECT_EMPTY_RESPONSE'|'ERROR_VAST_REDIRECT_MULTIPLE_VAST'|'ERROR_VAST_REDIRECT_FAILED'|'ERROR_VAST_MISSING_MEDIAFILES'|'ERROR_VAST_MISSING_CREATIVES'|'ERROR_VAST_MISSING_OVERLAYS'|'ERROR_VAST_MISSING_IMPRESSION'|'ERROR_VAST_INVALID_VAST_AD_TAG_URI'|'ERROR_VAST_MULTIPLE_TRACKING_EVENTS'|'ERROR_VAST_MULTIPLE_LINEAR'|'ERROR_VAST_INVALID_MEDIA_FILE'|'ERROR_FIRING_BEACON_FAILED'|'ERROR_PERSONALIZATION_DISABLED'|'VOD_TIME_BASED_AVAIL_PLAN_VAST_RESPONSE_FOR_OFFSET'|'VOD_TIME_BASED_AVAIL_PLAN_SUCCESS'|'VOD_TIME_BASED_AVAIL_PLAN_WARNING_NO_ADVERTISEMENTS'|'INTERSTITIAL_VOD_SUCCESS'|'INTERSTITIAL_VOD_FAILURE'>|null $ExcludeEventTypes
 */
class AdsInteractionLog extends Shape
{
    /**
     * @param array{
     *     PublishOptInEventTypes?: list<'RAW_ADS_RESPONSE'>|null,
     *     ExcludeEventTypes?: list<'AD_MARKER_FOUND'|'NON_AD_MARKER_FOUND'|'MAKING_ADS_REQUEST'|'MODIFIED_TARGET_URL'|'VAST_REDIRECT'|'EMPTY_VAST_RESPONSE'|'EMPTY_VMAP_RESPONSE'|'VAST_RESPONSE'|'REDIRECTED_VAST_RESPONSE'|'FILLED_AVAIL'|'FILLED_OVERLAY_AVAIL'|'BEACON_FIRED'|'WARNING_NO_ADVERTISEMENTS'|'WARNING_VPAID_AD_DROPPED'|'WARNING_URL_VARIABLE_SUBSTITUTION_FAILED'|'ERROR_UNKNOWN'|'ERROR_UNKNOWN_HOST'|'ERROR_DISALLOWED_HOST'|'ERROR_ADS_IO'|'ERROR_ADS_TIMEOUT'|'ERROR_ADS_RESPONSE_PARSE'|'ERROR_ADS_RESPONSE_UNKNOWN_ROOT_ELEMENT'|'ERROR_ADS_INVALID_RESPONSE'|'ERROR_VAST_REDIRECT_EMPTY_RESPONSE'|'ERROR_VAST_REDIRECT_MULTIPLE_VAST'|'ERROR_VAST_REDIRECT_FAILED'|'ERROR_VAST_MISSING_MEDIAFILES'|'ERROR_VAST_MISSING_CREATIVES'|'ERROR_VAST_MISSING_OVERLAYS'|'ERROR_VAST_MISSING_IMPRESSION'|'ERROR_VAST_INVALID_VAST_AD_TAG_URI'|'ERROR_VAST_MULTIPLE_TRACKING_EVENTS'|'ERROR_VAST_MULTIPLE_LINEAR'|'ERROR_VAST_INVALID_MEDIA_FILE'|'ERROR_FIRING_BEACON_FAILED'|'ERROR_PERSONALIZATION_DISABLED'|'VOD_TIME_BASED_AVAIL_PLAN_VAST_RESPONSE_FOR_OFFSET'|'VOD_TIME_BASED_AVAIL_PLAN_SUCCESS'|'VOD_TIME_BASED_AVAIL_PLAN_WARNING_NO_ADVERTISEMENTS'|'INTERSTITIAL_VOD_SUCCESS'|'INTERSTITIAL_VOD_FAILURE'>|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
