<?php

namespace Sunaoka\Aws\Structures\WorkSpaces\CreateWorkspaceBundle\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'VALUE'|'STANDARD'|'PERFORMANCE'|'POWER'|'GRAPHICS'|'POWERPRO'|'GENERALPURPOSE_4XLARGE'|'GENERALPURPOSE_8XLARGE'|'GRAPHICSPRO'|'GRAPHICS_G4DN'|'GRAPHICSPRO_G4DN'|'GRAPHICS_G6_XLARGE'|'GRAPHICS_G6_2XLARGE'|'GRAPHICS_G6_4XLARGE'|'GRAPHICS_G6_8XLARGE'|'GRAPHICS_G6_16XLARGE'|'GRAPHICS_GR6_4XLARGE'|'GRAPHICS_GR6_8XLARGE'|'GRAPHICS_G6F_LARGE'|'GRAPHICS_G6F_XLARGE'|'GRAPHICS_G6F_2XLARGE'|'GRAPHICS_G6F_4XLARGE'|'GRAPHICS_GR6F_4XLARGE'|null $Name
 */
class ComputeType extends Shape
{
    /**
     * @param array{Name?: 'VALUE'|'STANDARD'|'PERFORMANCE'|'POWER'|'GRAPHICS'|'POWERPRO'|'GENERALPURPOSE_4XLARGE'|'GENERALPURPOSE_8XLARGE'|'GRAPHICSPRO'|'GRAPHICS_G4DN'|'GRAPHICSPRO_G4DN'|'GRAPHICS_G6_XLARGE'|'GRAPHICS_G6_2XLARGE'|'GRAPHICS_G6_4XLARGE'|'GRAPHICS_G6_8XLARGE'|'GRAPHICS_G6_16XLARGE'|'GRAPHICS_GR6_4XLARGE'|'GRAPHICS_GR6_8XLARGE'|'GRAPHICS_G6F_LARGE'|'GRAPHICS_G6F_XLARGE'|'GRAPHICS_G6F_2XLARGE'|'GRAPHICS_G6F_4XLARGE'|'GRAPHICS_GR6F_4XLARGE'|null} $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
