<?php

namespace Sunaoka\Aws\Structures\MediaPackageV2\UpdateOriginEndpoint\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property list<'SPLICE_INSERT'|'BREAK'|'PROVIDER_ADVERTISEMENT'|'DISTRIBUTOR_ADVERTISEMENT'|'PROVIDER_PLACEMENT_OPPORTUNITY'|'DISTRIBUTOR_PLACEMENT_OPPORTUNITY'|'PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY'|'DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY'|'PROGRAM'|'CHAPTER'|'UNSCHEDULED_EVENT'|'ALTERNATE_CONTENT_OPPORTUNITY'|'NETWORK'|'PROVIDER_PROMO'|'DISTRIBUTOR_PROMO'|'PROVIDER_AD_BLOCK'|'DISTRIBUTOR_AD_BLOCK'>|null $ScteFilter
 * @property 'NONE'|'ALL'|'MATCHES_FILTER'|null $ScteInSegments
 * @property list<'PROGRAM'|'CHAPTER'|'UNSCHEDULED_EVENT'|'ALTERNATE_CONTENT_OPPORTUNITY'|'NETWORK'>|null $CustomAdTypes
 */
class Scte extends Shape
{
    /**
     * @param array{
     *     ScteFilter?: list<'SPLICE_INSERT'|'BREAK'|'PROVIDER_ADVERTISEMENT'|'DISTRIBUTOR_ADVERTISEMENT'|'PROVIDER_PLACEMENT_OPPORTUNITY'|'DISTRIBUTOR_PLACEMENT_OPPORTUNITY'|'PROVIDER_OVERLAY_PLACEMENT_OPPORTUNITY'|'DISTRIBUTOR_OVERLAY_PLACEMENT_OPPORTUNITY'|'PROGRAM'|'CHAPTER'|'UNSCHEDULED_EVENT'|'ALTERNATE_CONTENT_OPPORTUNITY'|'NETWORK'|'PROVIDER_PROMO'|'DISTRIBUTOR_PROMO'|'PROVIDER_AD_BLOCK'|'DISTRIBUTOR_AD_BLOCK'>|null,
     *     ScteInSegments?: 'NONE'|'ALL'|'MATCHES_FILTER'|null,
     *     CustomAdTypes?: list<'PROGRAM'|'CHAPTER'|'UNSCHEDULED_EVENT'|'ALTERNATE_CONTENT_OPPORTUNITY'|'NETWORK'>|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
