<?php

namespace Sunaoka\Aws\Structures\Glue\GetConnections\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property list<string>|null $MatchCriteria
 * @property 'JDBC'|'SFTP'|'MONGODB'|'KAFKA'|'NETWORK'|'MARKETPLACE'|'CUSTOM'|'SALESFORCE'|'VIEW_VALIDATION_REDSHIFT'|'VIEW_VALIDATION_ATHENA'|'GOOGLEADS'|'GOOGLESHEETS'|'GOOGLEANALYTICS4'|'SERVICENOW'|'MARKETO'|'SAPODATA'|'ZENDESK'|'JIRACLOUD'|'NETSUITEERP'|'HUBSPOT'|'FACEBOOKADS'|'INSTAGRAMADS'|'ZOHOCRM'|'SALESFORCEPARDOT'|'SALESFORCEMARKETINGCLOUD'|'ADOBEANALYTICS'|'SLACK'|'LINKEDIN'|'MIXPANEL'|'ASANA'|'STRIPE'|'SMARTSHEET'|'DATADOG'|'WOOCOMMERCE'|'INTERCOM'|'SNAPCHATADS'|'PAYPAL'|'QUICKBOOKS'|'FACEBOOKPAGEINSIGHTS'|'FRESHDESK'|'TWILIO'|'DOCUSIGNMONITOR'|'FRESHSALES'|'ZOOM'|'GOOGLESEARCHCONSOLE'|'SALESFORCECOMMERCECLOUD'|'SAPCONCUR'|'DYNATRACE'|'MICROSOFTDYNAMIC365FINANCEANDOPS'|'MICROSOFTTEAMS'|'BLACKBAUDRAISEREDGENXT'|'MAILCHIMP'|'GITLAB'|'PENDO'|'PRODUCTBOARD'|'CIRCLECI'|'PIPEDIVE'|'SENDGRID'|'AZURECOSMOS'|'AZURESQL'|'BIGQUERY'|'BLACKBAUD'|'CLOUDERAHIVE'|'CLOUDERAIMPALA'|'CLOUDWATCH'|'CLOUDWATCHMETRICS'|'CMDB'|'DATALAKEGEN2'|'DB2'|'DB2AS400'|'DOCUMENTDB'|'DOMO'|'DYNAMODB'|'GOOGLECLOUDSTORAGE'|'HBASE'|'KUSTOMER'|'MICROSOFTDYNAMICS365CRM'|'MONDAY'|'MYSQL'|'OKTA'|'OPENSEARCH'|'ORACLE'|'PIPEDRIVE'|'POSTGRESQL'|'SAPHANA'|'SQLSERVER'|'SYNAPSE'|'TERADATA'|'TERADATANOS'|'TIMESTREAM'|'TPCDS'|'VERTICA'|null $ConnectionType
 * @property int<1, 2>|null $ConnectionSchemaVersion
 */
class GetConnectionsFilter extends Shape
{
    /**
     * @param array{
     *     MatchCriteria?: list<string>|null,
     *     ConnectionType?: 'JDBC'|'SFTP'|'MONGODB'|'KAFKA'|'NETWORK'|'MARKETPLACE'|'CUSTOM'|'SALESFORCE'|'VIEW_VALIDATION_REDSHIFT'|'VIEW_VALIDATION_ATHENA'|'GOOGLEADS'|'GOOGLESHEETS'|'GOOGLEANALYTICS4'|'SERVICENOW'|'MARKETO'|'SAPODATA'|'ZENDESK'|'JIRACLOUD'|'NETSUITEERP'|'HUBSPOT'|'FACEBOOKADS'|'INSTAGRAMADS'|'ZOHOCRM'|'SALESFORCEPARDOT'|'SALESFORCEMARKETINGCLOUD'|'ADOBEANALYTICS'|'SLACK'|'LINKEDIN'|'MIXPANEL'|'ASANA'|'STRIPE'|'SMARTSHEET'|'DATADOG'|'WOOCOMMERCE'|'INTERCOM'|'SNAPCHATADS'|'PAYPAL'|'QUICKBOOKS'|'FACEBOOKPAGEINSIGHTS'|'FRESHDESK'|'TWILIO'|'DOCUSIGNMONITOR'|'FRESHSALES'|'ZOOM'|'GOOGLESEARCHCONSOLE'|'SALESFORCECOMMERCECLOUD'|'SAPCONCUR'|'DYNATRACE'|'MICROSOFTDYNAMIC365FINANCEANDOPS'|'MICROSOFTTEAMS'|'BLACKBAUDRAISEREDGENXT'|'MAILCHIMP'|'GITLAB'|'PENDO'|'PRODUCTBOARD'|'CIRCLECI'|'PIPEDIVE'|'SENDGRID'|'AZURECOSMOS'|'AZURESQL'|'BIGQUERY'|'BLACKBAUD'|'CLOUDERAHIVE'|'CLOUDERAIMPALA'|'CLOUDWATCH'|'CLOUDWATCHMETRICS'|'CMDB'|'DATALAKEGEN2'|'DB2'|'DB2AS400'|'DOCUMENTDB'|'DOMO'|'DYNAMODB'|'GOOGLECLOUDSTORAGE'|'HBASE'|'KUSTOMER'|'MICROSOFTDYNAMICS365CRM'|'MONDAY'|'MYSQL'|'OKTA'|'OPENSEARCH'|'ORACLE'|'PIPEDRIVE'|'POSTGRESQL'|'SAPHANA'|'SQLSERVER'|'SYNAPSE'|'TERADATA'|'TERADATANOS'|'TIMESTREAM'|'TPCDS'|'VERTICA'|null,
     *     ConnectionSchemaVersion?: int<1, 2>|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
