<?php

namespace Sunaoka\Aws\Structures\drs\DescribeJobLogItems\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'JOB_START'|'SERVER_SKIPPED'|'CLEANUP_START'|'CLEANUP_END'|'CLEANUP_FAIL'|'SNAPSHOT_START'|'SNAPSHOT_END'|'SNAPSHOT_FAIL'|'USING_PREVIOUS_SNAPSHOT'|'USING_PREVIOUS_SNAPSHOT_FAILED'|'CONVERSION_START'|'CONVERSION_END'|'CONVERSION_FAIL'|'LAUNCH_START'|'LAUNCH_FAILED'|'JOB_CANCEL'|'JOB_END'|'DEPLOY_NETWORK_CONFIGURATION_START'|'DEPLOY_NETWORK_CONFIGURATION_END'|'DEPLOY_NETWORK_CONFIGURATION_FAILED'|'UPDATE_NETWORK_CONFIGURATION_START'|'UPDATE_NETWORK_CONFIGURATION_END'|'UPDATE_NETWORK_CONFIGURATION_FAILED'|'UPDATE_LAUNCH_TEMPLATE_START'|'UPDATE_LAUNCH_TEMPLATE_END'|'UPDATE_LAUNCH_TEMPLATE_FAILED'|'NETWORK_RECOVERY_FAIL' $event
 * @property JobLogEventData $eventData
 * @property string $logDateTime
 */
class JobLog extends Shape
{
    /**
     * @param array{
     *     event?: 'JOB_START'|'SERVER_SKIPPED'|'CLEANUP_START'|'CLEANUP_END'|'CLEANUP_FAIL'|'SNAPSHOT_START'|'SNAPSHOT_END'|'SNAPSHOT_FAIL'|'USING_PREVIOUS_SNAPSHOT'|'USING_PREVIOUS_SNAPSHOT_FAILED'|'CONVERSION_START'|'CONVERSION_END'|'CONVERSION_FAIL'|'LAUNCH_START'|'LAUNCH_FAILED'|'JOB_CANCEL'|'JOB_END'|'DEPLOY_NETWORK_CONFIGURATION_START'|'DEPLOY_NETWORK_CONFIGURATION_END'|'DEPLOY_NETWORK_CONFIGURATION_FAILED'|'UPDATE_NETWORK_CONFIGURATION_START'|'UPDATE_NETWORK_CONFIGURATION_END'|'UPDATE_NETWORK_CONFIGURATION_FAILED'|'UPDATE_LAUNCH_TEMPLATE_START'|'UPDATE_LAUNCH_TEMPLATE_END'|'UPDATE_LAUNCH_TEMPLATE_FAILED'|'NETWORK_RECOVERY_FAIL',
     *     eventData?: JobLogEventData,
     *     logDateTime?: string
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
