<?php

namespace Sunaoka\Aws\Structures\Outposts\CreateQuote\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property string|null $StatusMessage
 * @property 'OUTPOST_ACTIVE_CHECK_ERROR'|'MAXIMUM_ALLOWED_ORDERS_CHECK_ERROR'|'VALID_ZIP_CODE_CHECK_ERROR'|'RACK_PHYSICAL_PROPERTIES_CHECK_ERROR'|'OPERATING_ADDRESS_EXISTENCE_CHECK_ERROR'|'SHIPPING_ADDRESS_EXISTENCE_CHECK_ERROR'|'COUNTRY_CODE_MISMATCH_CHECK_ERROR'|'OUTPOST_GENERATION_MISMATCH_ERROR'|'UNSUPPORTED'|'OUTPOST_ID_MISSING_ON_QUOTE_ERROR'|'ENTERPRISE_SUPPORT_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_NAME_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_NUMBER_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_INFO_ERROR'|'OUTPOST_STATE_CHANGED_ERROR'|'OUTPOST_NOT_FOUND_ERROR'|'OUTPOST_RENEWAL_REQUIRED_ERROR'|null $OrderingRequirementType
 * @property 'PASS'|'FAIL'|'EXEMPT'|null $Status
 */
class OrderingRequirement extends Shape
{
    /**
     * @param array{
     *     StatusMessage?: string|null,
     *     OrderingRequirementType?: 'OUTPOST_ACTIVE_CHECK_ERROR'|'MAXIMUM_ALLOWED_ORDERS_CHECK_ERROR'|'VALID_ZIP_CODE_CHECK_ERROR'|'RACK_PHYSICAL_PROPERTIES_CHECK_ERROR'|'OPERATING_ADDRESS_EXISTENCE_CHECK_ERROR'|'SHIPPING_ADDRESS_EXISTENCE_CHECK_ERROR'|'COUNTRY_CODE_MISMATCH_CHECK_ERROR'|'OUTPOST_GENERATION_MISMATCH_ERROR'|'UNSUPPORTED'|'OUTPOST_ID_MISSING_ON_QUOTE_ERROR'|'ENTERPRISE_SUPPORT_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_NAME_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_NUMBER_ERROR'|'SHIPPING_ADDRESS_MISSING_CONTACT_INFO_ERROR'|'OUTPOST_STATE_CHANGED_ERROR'|'OUTPOST_NOT_FOUND_ERROR'|'OUTPOST_RENEWAL_REQUIRED_ERROR'|null,
     *     Status?: 'PASS'|'FAIL'|'EXEMPT'|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
