<?php

namespace Sunaoka\Aws\Structures\Resiliencehubv2\ListServiceEvents\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property string $eventId
 * @property \Aws\Api\DateTimeResult $timestamp
 * @property 'SERVICE_CREATED'|'SERVICE_DELETED'|'SERVICE_SYSTEM_ASSOCIATED'|'SERVICE_SYSTEM_DISASSOCIATED'|'SERVICE_RESOURCES_ASSOCIATED'|'SERVICE_RESOURCES_DISASSOCIATED'|'SERVICE_WORKFLOW_UPDATED'|'SERVICE_INPUT_SOURCES_UPDATED'|'SERVICE_POLICY_ASSOCIATED'|'SERVICE_POLICY_DISASSOCIATED'|'SERVICE_FUNCTION_CREATED'|'SERVICE_FUNCTION_UPDATED'|'SERVICE_FUNCTION_DELETED'|'SERVICE_FUNCTION_RESOURCES_ADDED'|'SERVICE_FUNCTION_RESOURCES_REMOVED'|'SERVICE_ACHIEVABILITY_UPDATED'|'ASSERTION_CREATED'|'ASSERTION_UPDATED'|'ASSERTION_DELETED' $eventType
 * @property string $serviceArn
 * @property EventActor $actor
 * @property ServiceEventDetails $eventDetails
 */
class ServiceEvent extends Shape
{
    /**
     * @param array{
     *     eventId: string,
     *     timestamp: \Aws\Api\DateTimeResult,
     *     eventType: 'SERVICE_CREATED'|'SERVICE_DELETED'|'SERVICE_SYSTEM_ASSOCIATED'|'SERVICE_SYSTEM_DISASSOCIATED'|'SERVICE_RESOURCES_ASSOCIATED'|'SERVICE_RESOURCES_DISASSOCIATED'|'SERVICE_WORKFLOW_UPDATED'|'SERVICE_INPUT_SOURCES_UPDATED'|'SERVICE_POLICY_ASSOCIATED'|'SERVICE_POLICY_DISASSOCIATED'|'SERVICE_FUNCTION_CREATED'|'SERVICE_FUNCTION_UPDATED'|'SERVICE_FUNCTION_DELETED'|'SERVICE_FUNCTION_RESOURCES_ADDED'|'SERVICE_FUNCTION_RESOURCES_REMOVED'|'SERVICE_ACHIEVABILITY_UPDATED'|'ASSERTION_CREATED'|'ASSERTION_UPDATED'|'ASSERTION_DELETED',
     *     serviceArn: string,
     *     actor: EventActor,
     *     eventDetails: ServiceEventDetails
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
