<?php

namespace Sunaoka\Aws\Structures\DevOpsGuru\ListMonitoredResources\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'FULL_PERMISSION'|'MISSING_PERMISSION' $ResourcePermission
 * @property list<'LOG_GROUPS'|'CLOUDFRONT_DISTRIBUTION'|'DYNAMODB_TABLE'|'EC2_NAT_GATEWAY'|'ECS_CLUSTER'|'ECS_SERVICE'|'EKS_CLUSTER'|'ELASTIC_BEANSTALK_ENVIRONMENT'|'ELASTIC_LOAD_BALANCER_LOAD_BALANCER'|'ELASTIC_LOAD_BALANCING_V2_LOAD_BALANCER'|'ELASTIC_LOAD_BALANCING_V2_TARGET_GROUP'|'ELASTICACHE_CACHE_CLUSTER'|'ELASTICSEARCH_DOMAIN'|'KINESIS_STREAM'|'LAMBDA_FUNCTION'|'OPEN_SEARCH_SERVICE_DOMAIN'|'RDS_DB_INSTANCE'|'RDS_DB_CLUSTER'|'REDSHIFT_CLUSTER'|'ROUTE53_HOSTED_ZONE'|'ROUTE53_HEALTH_CHECK'|'S3_BUCKET'|'SAGEMAKER_ENDPOINT'|'SNS_TOPIC'|'SQS_QUEUE'|'STEP_FUNCTIONS_ACTIVITY'|'STEP_FUNCTIONS_STATE_MACHINE'> $ResourceTypeFilters
 */
class ListMonitoredResourcesFilters extends Shape
{
    /**
     * @param array{
     *     ResourcePermission: 'FULL_PERMISSION'|'MISSING_PERMISSION',
     *     ResourceTypeFilters: list<'LOG_GROUPS'|'CLOUDFRONT_DISTRIBUTION'|'DYNAMODB_TABLE'|'EC2_NAT_GATEWAY'|'ECS_CLUSTER'|'ECS_SERVICE'|'EKS_CLUSTER'|'ELASTIC_BEANSTALK_ENVIRONMENT'|'ELASTIC_LOAD_BALANCER_LOAD_BALANCER'|'ELASTIC_LOAD_BALANCING_V2_LOAD_BALANCER'|'ELASTIC_LOAD_BALANCING_V2_TARGET_GROUP'|'ELASTICACHE_CACHE_CLUSTER'|'ELASTICSEARCH_DOMAIN'|'KINESIS_STREAM'|'LAMBDA_FUNCTION'|'OPEN_SEARCH_SERVICE_DOMAIN'|'RDS_DB_INSTANCE'|'RDS_DB_CLUSTER'|'REDSHIFT_CLUSTER'|'ROUTE53_HOSTED_ZONE'|'ROUTE53_HEALTH_CHECK'|'S3_BUCKET'|'SAGEMAKER_ENDPOINT'|'SNS_TOPIC'|'SQS_QUEUE'|'STEP_FUNCTIONS_ACTIVITY'|'STEP_FUNCTIONS_STATE_MACHINE'>
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
