<?php

namespace Sunaoka\Aws\Structures\Firehose\DescribeDeliveryStream\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'VPC_ENDPOINT_SERVICE_NAME_NOT_FOUND'|'VPC_INTERFACE_ENDPOINT_SERVICE_ACCESS_DENIED'|'RETIRE_KMS_GRANT_FAILED'|'CREATE_KMS_GRANT_FAILED'|'KMS_ACCESS_DENIED'|'DISABLED_KMS_KEY'|'INVALID_KMS_KEY'|'KMS_KEY_NOT_FOUND'|'KMS_OPT_IN_REQUIRED'|'CREATE_ENI_FAILED'|'DELETE_ENI_FAILED'|'SUBNET_NOT_FOUND'|'SECURITY_GROUP_NOT_FOUND'|'ENI_ACCESS_DENIED'|'SUBNET_ACCESS_DENIED'|'SECURITY_GROUP_ACCESS_DENIED'|'UNKNOWN_ERROR' $Type
 * @property string $Details
 */
class FailureDescription extends Shape
{
    /**
     * @param array{
     *     Type: 'VPC_ENDPOINT_SERVICE_NAME_NOT_FOUND'|'VPC_INTERFACE_ENDPOINT_SERVICE_ACCESS_DENIED'|'RETIRE_KMS_GRANT_FAILED'|'CREATE_KMS_GRANT_FAILED'|'KMS_ACCESS_DENIED'|'DISABLED_KMS_KEY'|'INVALID_KMS_KEY'|'KMS_KEY_NOT_FOUND'|'KMS_OPT_IN_REQUIRED'|'CREATE_ENI_FAILED'|'DELETE_ENI_FAILED'|'SUBNET_NOT_FOUND'|'SECURITY_GROUP_NOT_FOUND'|'ENI_ACCESS_DENIED'|'SUBNET_ACCESS_DENIED'|'SECURITY_GROUP_ACCESS_DENIED'|'UNKNOWN_ERROR',
     *     Details: string
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
