<?php

namespace Sunaoka\Aws\Structures\PartnerCentralAccount\StartProfileUpdateTask\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property string $DisplayName
 * @property string $Description
 * @property string $WebsiteUrl
 * @property string $LogoUrl
 * @property 'SOFTWARE_PRODUCTS'|'CONSULTING_SERVICES'|'PROFESSIONAL_SERVICES'|'MANAGED_SERVICES'|'HARDWARE_PRODUCTS'|'COMMUNICATION_SERVICES'|'VALUE_ADDED_RESALE_AWS_SERVICES'|'TRAINING_SERVICES' $PrimarySolutionType
 * @property list<'AGRICULTURE_MINING'|'BIOTECHNOLOGY'|'BUSINESS_CONSUMER_SERVICES'|'BUSINESS_SERV'|'COMMUNICATIONS'|'COMPUTER_HARDWARE'|'COMPUTERS_ELECTRONICS'|'COMPUTER_SOFTWARE'|'CONSUMER_GOODS'|'CONSUMER_RELATED'|'EDUCATION'|'ENERGY_UTILITIES'|'FINANCIAL_SERVICES'|'GAMING'|'GOVERNMENT'|'GOVERNMENT_EDUCATION_PUBLIC_SERVICES'|'HEALTHCARE'|'HEALTHCARE_PHARMACEUTICALS_BIOTECH'|'INDUSTRIAL_ENERGY'|'INTERNET_SPECIFIC'|'LIFE_SCIENCES'|'MANUFACTURING'|'MEDIA_ENTERTAINMENT_LEISURE'|'MEDIA_ENTERTAINMENT'|'MEDICAL_HEALTH'|'NON_PROFIT_ORGANIZATION'|'OTHER'|'PROFESSIONAL_SERVICES'|'REAL_ESTATE_CONSTRUCTION'|'RETAIL'|'RETAIL_WHOLESALE_DISTRIBUTION'|'SEMICONDUCTOR_ELECTR'|'SOFTWARE_INTERNET'|'TELECOMMUNICATIONS'|'TRANSPORTATION_LOGISTICS'|'TRAVEL_HOSPITALITY'|'WHOLESALE_DISTRIBUTION'> $IndustrySegments
 * @property string $TranslationSourceLocale
 * @property list<LocalizedContent>|null $LocalizedContents
 */
class TaskDetails extends Shape
{
    /**
     * @param array{
     *     DisplayName: string,
     *     Description: string,
     *     WebsiteUrl: string,
     *     LogoUrl: string,
     *     PrimarySolutionType: 'SOFTWARE_PRODUCTS'|'CONSULTING_SERVICES'|'PROFESSIONAL_SERVICES'|'MANAGED_SERVICES'|'HARDWARE_PRODUCTS'|'COMMUNICATION_SERVICES'|'VALUE_ADDED_RESALE_AWS_SERVICES'|'TRAINING_SERVICES',
     *     IndustrySegments: list<'AGRICULTURE_MINING'|'BIOTECHNOLOGY'|'BUSINESS_CONSUMER_SERVICES'|'BUSINESS_SERV'|'COMMUNICATIONS'|'COMPUTER_HARDWARE'|'COMPUTERS_ELECTRONICS'|'COMPUTER_SOFTWARE'|'CONSUMER_GOODS'|'CONSUMER_RELATED'|'EDUCATION'|'ENERGY_UTILITIES'|'FINANCIAL_SERVICES'|'GAMING'|'GOVERNMENT'|'GOVERNMENT_EDUCATION_PUBLIC_SERVICES'|'HEALTHCARE'|'HEALTHCARE_PHARMACEUTICALS_BIOTECH'|'INDUSTRIAL_ENERGY'|'INTERNET_SPECIFIC'|'LIFE_SCIENCES'|'MANUFACTURING'|'MEDIA_ENTERTAINMENT_LEISURE'|'MEDIA_ENTERTAINMENT'|'MEDICAL_HEALTH'|'NON_PROFIT_ORGANIZATION'|'OTHER'|'PROFESSIONAL_SERVICES'|'REAL_ESTATE_CONSTRUCTION'|'RETAIL'|'RETAIL_WHOLESALE_DISTRIBUTION'|'SEMICONDUCTOR_ELECTR'|'SOFTWARE_INTERNET'|'TELECOMMUNICATIONS'|'TRANSPORTATION_LOGISTICS'|'TRAVEL_HOSPITALITY'|'WHOLESALE_DISTRIBUTION'>,
     *     TranslationSourceLocale: string,
     *     LocalizedContents?: list<LocalizedContent>|null
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
