<?php

namespace Sunaoka\Aws\Structures\GameLift\CreateContainerGroupDefinition\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property list<'AUDIT_CONTROL'|'AUDIT_WRITE'|'BLOCK_SUSPEND'|'CHOWN'|'DAC_OVERRIDE'|'DAC_READ_SEARCH'|'FOWNER'|'FSETID'|'IPC_LOCK'|'IPC_OWNER'|'KILL'|'LEASE'|'LINUX_IMMUTABLE'|'MAC_ADMIN'|'MAC_OVERRIDE'|'MKNOD'|'NET_ADMIN'|'NET_BIND_SERVICE'|'NET_BROADCAST'|'NET_RAW'|'SETFCAP'|'SETGID'|'SETPCAP'|'SETUID'|'SYS_ADMIN'|'SYS_BOOT'|'SYS_CHROOT'|'SYS_MODULE'|'SYS_NICE'|'SYS_PACCT'|'SYS_PTRACE'|'SYS_RAWIO'|'SYS_RESOURCE'|'SYS_TIME'|'SYS_TTY_CONFIG'|'SYSLOG'|'WAKE_ALARM'>|null $Include
 */
class LinuxCapabilities extends Shape
{
    /**
     * @param array{Include?: list<'AUDIT_CONTROL'|'AUDIT_WRITE'|'BLOCK_SUSPEND'|'CHOWN'|'DAC_OVERRIDE'|'DAC_READ_SEARCH'|'FOWNER'|'FSETID'|'IPC_LOCK'|'IPC_OWNER'|'KILL'|'LEASE'|'LINUX_IMMUTABLE'|'MAC_ADMIN'|'MAC_OVERRIDE'|'MKNOD'|'NET_ADMIN'|'NET_BIND_SERVICE'|'NET_BROADCAST'|'NET_RAW'|'SETFCAP'|'SETGID'|'SETPCAP'|'SETUID'|'SYS_ADMIN'|'SYS_BOOT'|'SYS_CHROOT'|'SYS_MODULE'|'SYS_NICE'|'SYS_PACCT'|'SYS_PTRACE'|'SYS_RAWIO'|'SYS_RESOURCE'|'SYS_TIME'|'SYS_TTY_CONFIG'|'SYSLOG'|'WAKE_ALARM'>|null} $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
