<?php

namespace Sunaoka\Aws\Structures\AccessAnalyzer\GetGeneratedPolicy\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'AUTHORIZATION_ERROR'|'RESOURCE_NOT_FOUND_ERROR'|'SERVICE_QUOTA_EXCEEDED_ERROR'|'SERVICE_ERROR'|'CANCELED_JOB_ERROR'|'INVALID_SERVICE_LINKED_ROLE'|'INSUFFICIENT_PERMISSIONS_ERROR'|'ORGANIZATION_ACCESS_DENIED_ERROR'|'INVALID_TARGET_ERROR'|'INVALID_POLICY_PREVIEW_CONFIGURATION'|'INVALID_ORGANIZATION_CONFIGURATION'|'S3_BUCKET_NOT_FOUND_ERROR'|'S3_BUCKET_PERMISSION_ERROR' $code
 * @property string $message
 */
class JobError extends Shape
{
    /**
     * @param array{
     *     code: 'AUTHORIZATION_ERROR'|'RESOURCE_NOT_FOUND_ERROR'|'SERVICE_QUOTA_EXCEEDED_ERROR'|'SERVICE_ERROR'|'CANCELED_JOB_ERROR'|'INVALID_SERVICE_LINKED_ROLE'|'INSUFFICIENT_PERMISSIONS_ERROR'|'ORGANIZATION_ACCESS_DENIED_ERROR'|'INVALID_TARGET_ERROR'|'INVALID_POLICY_PREVIEW_CONFIGURATION'|'INVALID_ORGANIZATION_CONFIGURATION'|'S3_BUCKET_NOT_FOUND_ERROR'|'S3_BUCKET_PERMISSION_ERROR',
     *     message: string
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
