<?php

namespace Sunaoka\Aws\Structures\ComputeOptimizer\ExportEC2InstanceRecommendations;

use Sunaoka\Aws\Structures\Request;

/**
 * @property list<string>|null $accountIds
 * @property list<Shapes\Filter>|null $filters
 * @property list<'AccountId'|'InstanceArn'|'InstanceName'|'Finding'|'FindingReasonCodes'|'LookbackPeriodInDays'|'CurrentInstanceType'|'UtilizationMetricsCpuMaximum'|'UtilizationMetricsMemoryMaximum'|'UtilizationMetricsEbsReadOpsPerSecondMaximum'|'UtilizationMetricsEbsWriteOpsPerSecondMaximum'|'UtilizationMetricsEbsReadBytesPerSecondMaximum'|'UtilizationMetricsEbsWriteBytesPerSecondMaximum'|'UtilizationMetricsDiskReadOpsPerSecondMaximum'|'UtilizationMetricsDiskWriteOpsPerSecondMaximum'|'UtilizationMetricsDiskReadBytesPerSecondMaximum'|'UtilizationMetricsDiskWriteBytesPerSecondMaximum'|'UtilizationMetricsNetworkInBytesPerSecondMaximum'|'UtilizationMetricsNetworkOutBytesPerSecondMaximum'|'UtilizationMetricsNetworkPacketsInPerSecondMaximum'|'UtilizationMetricsNetworkPacketsOutPerSecondMaximum'|'CurrentOnDemandPrice'|'CurrentStandardOneYearNoUpfrontReservedPrice'|'CurrentStandardThreeYearNoUpfrontReservedPrice'|'CurrentVCpus'|'CurrentMemory'|'CurrentStorage'|'CurrentNetwork'|'RecommendationOptionsInstanceType'|'RecommendationOptionsProjectedUtilizationMetricsCpuMaximum'|'RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum'|'RecommendationOptionsPlatformDifferences'|'RecommendationOptionsPerformanceRisk'|'RecommendationOptionsVcpus'|'RecommendationOptionsMemory'|'RecommendationOptionsStorage'|'RecommendationOptionsNetwork'|'RecommendationOptionsOnDemandPrice'|'RecommendationOptionsStandardOneYearNoUpfrontReservedPrice'|'RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice'|'RecommendationsSourcesRecommendationSourceArn'|'RecommendationsSourcesRecommendationSourceType'|'LastRefreshTimestamp'|'CurrentPerformanceRisk'|'RecommendationOptionsSavingsOpportunityPercentage'|'RecommendationOptionsEstimatedMonthlySavingsCurrency'|'RecommendationOptionsEstimatedMonthlySavingsValue'|'EffectiveRecommendationPreferencesCpuVendorArchitectures'|'EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics'|'EffectiveRecommendationPreferencesInferredWorkloadTypes'|'InferredWorkloadTypes'|'RecommendationOptionsMigrationEffort'|'EffectiveRecommendationPreferencesExternalMetricsSource'|'Tags'|'InstanceState'|'ExternalMetricStatusCode'|'ExternalMetricStatusReason'|'CurrentInstanceGpuInfo'|'RecommendationOptionsInstanceGpuInfo'|'UtilizationMetricsGpuPercentageMaximum'|'UtilizationMetricsGpuMemoryPercentageMaximum'|'RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum'|'RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum'|'Idle'|'EffectiveRecommendationPreferencesPreferredResources'|'EffectiveRecommendationPreferencesLookBackPeriod'|'EffectiveRecommendationPreferencesUtilizationPreferences'|'EffectiveRecommendationPreferencesSavingsEstimationMode'|'RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage'|'RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts'|'RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts'>|null $fieldsToExport
 * @property Shapes\S3DestinationConfig $s3DestinationConfig
 * @property 'Csv'|null $fileFormat
 * @property bool|null $includeMemberAccounts
 * @property Shapes\RecommendationPreferences|null $recommendationPreferences
 */
class ExportEC2InstanceRecommendationsRequest extends Request
{
    /**
     * @param array{
     *     accountIds?: list<string>|null,
     *     filters?: list<Shapes\Filter>|null,
     *     fieldsToExport?: list<'AccountId'|'InstanceArn'|'InstanceName'|'Finding'|'FindingReasonCodes'|'LookbackPeriodInDays'|'CurrentInstanceType'|'UtilizationMetricsCpuMaximum'|'UtilizationMetricsMemoryMaximum'|'UtilizationMetricsEbsReadOpsPerSecondMaximum'|'UtilizationMetricsEbsWriteOpsPerSecondMaximum'|'UtilizationMetricsEbsReadBytesPerSecondMaximum'|'UtilizationMetricsEbsWriteBytesPerSecondMaximum'|'UtilizationMetricsDiskReadOpsPerSecondMaximum'|'UtilizationMetricsDiskWriteOpsPerSecondMaximum'|'UtilizationMetricsDiskReadBytesPerSecondMaximum'|'UtilizationMetricsDiskWriteBytesPerSecondMaximum'|'UtilizationMetricsNetworkInBytesPerSecondMaximum'|'UtilizationMetricsNetworkOutBytesPerSecondMaximum'|'UtilizationMetricsNetworkPacketsInPerSecondMaximum'|'UtilizationMetricsNetworkPacketsOutPerSecondMaximum'|'CurrentOnDemandPrice'|'CurrentStandardOneYearNoUpfrontReservedPrice'|'CurrentStandardThreeYearNoUpfrontReservedPrice'|'CurrentVCpus'|'CurrentMemory'|'CurrentStorage'|'CurrentNetwork'|'RecommendationOptionsInstanceType'|'RecommendationOptionsProjectedUtilizationMetricsCpuMaximum'|'RecommendationOptionsProjectedUtilizationMetricsMemoryMaximum'|'RecommendationOptionsPlatformDifferences'|'RecommendationOptionsPerformanceRisk'|'RecommendationOptionsVcpus'|'RecommendationOptionsMemory'|'RecommendationOptionsStorage'|'RecommendationOptionsNetwork'|'RecommendationOptionsOnDemandPrice'|'RecommendationOptionsStandardOneYearNoUpfrontReservedPrice'|'RecommendationOptionsStandardThreeYearNoUpfrontReservedPrice'|'RecommendationsSourcesRecommendationSourceArn'|'RecommendationsSourcesRecommendationSourceType'|'LastRefreshTimestamp'|'CurrentPerformanceRisk'|'RecommendationOptionsSavingsOpportunityPercentage'|'RecommendationOptionsEstimatedMonthlySavingsCurrency'|'RecommendationOptionsEstimatedMonthlySavingsValue'|'EffectiveRecommendationPreferencesCpuVendorArchitectures'|'EffectiveRecommendationPreferencesEnhancedInfrastructureMetrics'|'EffectiveRecommendationPreferencesInferredWorkloadTypes'|'InferredWorkloadTypes'|'RecommendationOptionsMigrationEffort'|'EffectiveRecommendationPreferencesExternalMetricsSource'|'Tags'|'InstanceState'|'ExternalMetricStatusCode'|'ExternalMetricStatusReason'|'CurrentInstanceGpuInfo'|'RecommendationOptionsInstanceGpuInfo'|'UtilizationMetricsGpuPercentageMaximum'|'UtilizationMetricsGpuMemoryPercentageMaximum'|'RecommendationOptionsProjectedUtilizationMetricsGpuPercentageMaximum'|'RecommendationOptionsProjectedUtilizationMetricsGpuMemoryPercentageMaximum'|'Idle'|'EffectiveRecommendationPreferencesPreferredResources'|'EffectiveRecommendationPreferencesLookBackPeriod'|'EffectiveRecommendationPreferencesUtilizationPreferences'|'EffectiveRecommendationPreferencesSavingsEstimationMode'|'RecommendationOptionsSavingsOpportunityAfterDiscountsPercentage'|'RecommendationOptionsEstimatedMonthlySavingsCurrencyAfterDiscounts'|'RecommendationOptionsEstimatedMonthlySavingsValueAfterDiscounts'>|null,
     *     s3DestinationConfig: Shapes\S3DestinationConfig,
     *     fileFormat?: 'Csv'|null,
     *     includeMemberAccounts?: bool|null,
     *     recommendationPreferences?: Shapes\RecommendationPreferences|null
     * } $args
     */
    public function __construct(array $args)
    {
        $this->__data = $args;
    }
}
