<?php

namespace Sunaoka\Aws\Structures\NetworkManager\GetRouteAnalysis\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property 'CONNECTED'|'NOT_CONNECTED' $ResultCode
 * @property 'TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND'|'TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY'|'CYCLIC_PATH_DETECTED'|'TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND'|'ROUTE_NOT_FOUND'|'BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND'|'INACTIVE_ROUTE_FOR_DESTINATION_FOUND'|'TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH'|'MAX_HOPS_EXCEEDED'|'POSSIBLE_MIDDLEBOX'|'NO_DESTINATION_ARN_PROVIDED' $ReasonCode
 * @property array<string, string> $ReasonContext
 */
class RouteAnalysisCompletion extends Shape
{
    /**
     * @param array{
     *     ResultCode?: 'CONNECTED'|'NOT_CONNECTED',
     *     ReasonCode?: 'TRANSIT_GATEWAY_ATTACHMENT_NOT_FOUND'|'TRANSIT_GATEWAY_ATTACHMENT_NOT_IN_TRANSIT_GATEWAY'|'CYCLIC_PATH_DETECTED'|'TRANSIT_GATEWAY_ATTACHMENT_STABLE_ROUTE_TABLE_NOT_FOUND'|'ROUTE_NOT_FOUND'|'BLACKHOLE_ROUTE_FOR_DESTINATION_FOUND'|'INACTIVE_ROUTE_FOR_DESTINATION_FOUND'|'TRANSIT_GATEWAY_ATTACHMENT_ATTACH_ARN_NO_MATCH'|'MAX_HOPS_EXCEEDED'|'POSSIBLE_MIDDLEBOX'|'NO_DESTINATION_ARN_PROVIDED',
     *     ReasonContext?: array<string, string>
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
