<?php

namespace Sunaoka\Aws\Structures\BedrockDataAutomation\CreateDataAutomationProject\Shapes;

use Sunaoka\Aws\Structures\Shape;

/**
 * @property list<'ALL'|'ADDRESS'|'AGE'|'NAME'|'EMAIL'|'PHONE'|'USERNAME'|'PASSWORD'|'DRIVER_ID'|'LICENSE_PLATE'|'VEHICLE_IDENTIFICATION_NUMBER'|'CREDIT_DEBIT_CARD_CVV'|'CREDIT_DEBIT_CARD_EXPIRY'|'CREDIT_DEBIT_CARD_NUMBER'|'PIN'|'INTERNATIONAL_BANK_ACCOUNT_NUMBER'|'SWIFT_CODE'|'IP_ADDRESS'|'MAC_ADDRESS'|'URL'|'AWS_ACCESS_KEY'|'AWS_SECRET_KEY'|'US_BANK_ACCOUNT_NUMBER'|'US_BANK_ROUTING_NUMBER'|'US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER'|'US_PASSPORT_NUMBER'|'US_SOCIAL_SECURITY_NUMBER'|'CA_HEALTH_NUMBER'|'CA_SOCIAL_INSURANCE_NUMBER'|'UK_NATIONAL_HEALTH_SERVICE_NUMBER'|'UK_NATIONAL_INSURANCE_NUMBER'|'UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER'>|null $piiEntityTypes
 * @property 'PII'|'ENTITY_TYPE'|null $redactionMaskMode
 */
class PIIEntitiesConfiguration extends Shape
{
    /**
     * @param array{
     *     piiEntityTypes?: list<'ALL'|'ADDRESS'|'AGE'|'NAME'|'EMAIL'|'PHONE'|'USERNAME'|'PASSWORD'|'DRIVER_ID'|'LICENSE_PLATE'|'VEHICLE_IDENTIFICATION_NUMBER'|'CREDIT_DEBIT_CARD_CVV'|'CREDIT_DEBIT_CARD_EXPIRY'|'CREDIT_DEBIT_CARD_NUMBER'|'PIN'|'INTERNATIONAL_BANK_ACCOUNT_NUMBER'|'SWIFT_CODE'|'IP_ADDRESS'|'MAC_ADDRESS'|'URL'|'AWS_ACCESS_KEY'|'AWS_SECRET_KEY'|'US_BANK_ACCOUNT_NUMBER'|'US_BANK_ROUTING_NUMBER'|'US_INDIVIDUAL_TAX_IDENTIFICATION_NUMBER'|'US_PASSPORT_NUMBER'|'US_SOCIAL_SECURITY_NUMBER'|'CA_HEALTH_NUMBER'|'CA_SOCIAL_INSURANCE_NUMBER'|'UK_NATIONAL_HEALTH_SERVICE_NUMBER'|'UK_NATIONAL_INSURANCE_NUMBER'|'UK_UNIQUE_TAXPAYER_REFERENCE_NUMBER'>|null,
     *     redactionMaskMode?: 'PII'|'ENTITY_TYPE'|null
     * } $args
     */
    public function __construct(array $args = [])
    {
        $this->__data = $args;
    }
}
